### PR TITLE
add icon

### PR DESCRIPTION
**Pull request by jmarolf**

### CODE REVIEW

**Comment by RikkiGibson** [comment]
Was it intended for icon to be an empty file?

**Comment by jmarolf** [comment]
> Was it intended for icon to be an empty file?

It doesn't look empty to me?

**Comment by RikkiGibson** [comment]
on GitHub I see: 
image

**Comment by xt0rted** [comment]
Looks like a bug on the site, if you switch to the rich diff the image shows. I just reported this.

**Review by JoeRobich — APPROVED** [review]

**Pull request merged**
