### PR TITLE
System.CommandLine update

### PR DESCRIPTION
**Pull request by adamsitnik**
It's https://github.com/dotnet/format/pull/1826 but without merge conflict

### CODE REVIEW

**Comment by adamsitnik** [comment]
The Roslyn CI leg failed with package downgrade errors:

```log
2023-06-12T16:21:26.0407699Z D:\a\_temp\temp\roslyn\src\Workspaces\CoreTestUtilities\Microsoft.CodeAnalysis.Workspaces.Test.Utilities.csproj : error NU1605: Warning As Error: Detected package downgrade: Microsoft.VisualStudio.Threading from 17.3.33 to 17.3.1-alpha. Reference the package directly from the project to select a different version.  [D:\a\_temp\temp\roslyn\Roslyn.sln]
2023-06-12T16:21:26.0423444Z D:\a\_temp\temp\roslyn\src\Workspaces\CoreTestUtilities\Microsoft.CodeAnalysis.Workspaces.Test.Utilities.csproj : error NU1605:  Microsoft.CodeAnalysis.Workspaces.Test.Utilities -> Microsoft.CodeAnalysis.EditorFeatures.Common -> Microsoft.VisualStudio.Text.UI 17.3.198 -> Microsoft.VisualStudio.CoreUtility 17.3.198 -> Microsoft.VisualStudio.Threading (>= 17.3.33)  [D:\a\_temp\temp\roslyn\Roslyn.sln]
```

@JoeRobich @MichaelSimons Can it be related to my changes?

**Comment by MichaelSimons** [comment]
> @JoeRobich @MichaelSimons Can it be related to my changes?

I will defer to the repo owners.

**Review by sharwell — APPROVED** [review]

**Comment by MichaelSimons** [comment]
@marcpopMSFT, @baronfel  - FYI - this is one of the PRs were are going to need to coordinate flowing into the SDK in order to prevent breaking source-build.

**Comment by JoeRobich** [comment]
Changes have been reverted and new PR with these changes is open as https://github.com/dotnet/format/pull/1875

**Pull request merged**
