### PR TITLE
Add .pre-commit-hooks.yaml

### LINKED ISSUE #692: Support for pre-commit project
I wrote a hook for integrating with the [pre-commit](https://pre-commit.com/) project. It's here: https://github.com/jvstein/pre-commit-dotnet-format

I've been using it while developing on Linux, but haven't tested it on Windows or macOS. It's very much dependent on Docker, using a prebuilt docker image, because [pre-commit doesn't support C# yet](https://pre-commit.com/#supported-languages). I'd be very happy to integrate it into the project, but wasn't sure how to go about adding the docker dependency to the build system.

### PR DESCRIPTION
**Pull request by rkm**
Hi! [pre-commit](https://pre-commit.com/) now supports the dotnet language natively, which is stable as of [v2.9.0](https://github.com/pre-commit/pre-commit/releases/tag/v2.9.0). This PR adds a .pre-commit-hooks.yaml file so that dotnet format can be easily integrated into the workflows of developers who use pre-commit.

A sample `.pre-commit-config.yaml` to use this hook would then look like:

```yaml
repos:
-   repo: https://github.com/dotnet/format
    rev: "v4.0.130203"  # Or a more recent commit sha
    hooks:
    -   id: dotnet-format
        args: [--include]
```

I'm not sure how best to document this. Many maintainers add a section in their project README which provides a sample hook like the one above. I see from #692 that there are already some notes in the `docs/integrations.md` file, which I could add this to instead?

Closes #692

### CODE REVIEW

**Comment by chriselion** [comment]
Do you need to worry about https://github.com/dotnet/format/issues/699 for large projects?

I added [pre-commit support for my team's repo ](https://github.com/Unity-Technologies/ml-agents/pull/4362) a few months ago (before pre-commit supported dotnet natively), and wrote the files names to a temp file before passing to `dotnet-format` just to be on the safe side.

**Comment by jmarolf** [comment]
Thanks for this @rkm! In order to merge this we will need to update the [integrations.md](https://github.com/dotnet/format/blob/master/docs/integrations.md) file to talk about how you set this up. I'll review the pre-commit hook format so I can review this as best I can.

NOTE: `dotnet-format` supports both C# and Visual Basic so I think the `language` parameter should reflect that but I will need to do more research.

**Comment by chriselion** [comment]
The `language` field tells pre-commit what language to execute in, so I think that needs to stay as it is. But if you wanted to support Visual Basic file extensions, you could change the `types` to [`types_or`](https://pre-commit.com/#config-types_or) and add the extension there.

**Comment by chriselion** [comment]
@jmarolf Sorry for the bump, but any update on this?

**Comment by jmarolf** [comment]
To merge this we need [integrations.md](https://github.com/dotnet/format/blob/main/docs/integrations.md) to be updated to describe how someone consumed pre-commit hooks

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/format?pullRequest=872) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/format?pullRequest=872) before we can accept your contribution.<br/><br/>:x: rkm [sign now](https://cla.dotnetfoundation.org/dotnet/format?pullRequest=872)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/format?pullRequest=872) it.</sub>

**Comment by chriselion** [comment]
@jmarolf - I updated integrations.md, and also changed the file types so that Visual Basic files will be checked too.

**Review by JoeRobich — APPROVED** [review]
Thanks for contributing this!

**Comment by chriselion** [comment]
Thanks @JoeRobich! Any chance you'll be doing a release that includes this change anytime soon? I can update the integrations.md with a specific tag once it exists.

**Pull request merged**
