### PR TITLE
moving to different command structure

### PR DESCRIPTION
**Pull request by jmarolf**
This will require similar change to the dotnet/sdk repo once this is merged.

### CODE REVIEW

**Comment by jmarolf** [comment]
@JoeRobich I am [merging ](https://github.com/dotnet/format/pull/1286)main to release/6.x to clean up the changes a bit. May want to wait to review this until then.

One wild change I am making is having the 6.0 release target .NET 6. Let me know if there are giant unforseen problem here.

**Review by JoeRobich — APPROVED** [review]

**Comment by JoeRobich** [comment]
@jmarolf Any reason to hold on merging this?

**Comment by mihai-unity** [comment]
I just noticed this PR lost `-f` alias for `--folder`.

**Comment by JoeRobich** [comment]
@mihai-unity Yes, this was an intentional breaking change taken to better incorporate into the dotnet CLI. Breaking changes are being tracked on issue https://github.com/dotnet/format/issues/1292.

**Pull request merged**
