### PR TITLE
update system.commandline to unblock code flow

### PR DESCRIPTION
**Pull request by kasperk81**
to unblock https://github.com/dotnet/installer/pull/14991

@MichaelSimons @adamsitnik @JoeRobich

### CODE REVIEW

**Comment by kasperk81** [comment]
failures are not related to my change. please merge asap to unblock code flow

**Review by adamsitnik — APPROVED** [review]
The changes looks good to me, thank you for your help @kasperk81 !

**Comment by adamsitnik** [comment]
@MichaelSimons could you please merge this PR? I don't have the permissions to do it.

**Comment by kasperk81** [comment]
@jmarolf?

**Comment by kasperk81** [comment]
@danmoseley, @jaredpar, who is the owner of this repository? it is blocking the code flow.

**Comment by adamsitnik** [comment]
@kasperk81 the US based people were not responding last week due to Thanksgiving, I expect it's going to change this week ;)

**Review by arkalyanms — APPROVED** [review]

**Comment by arkalyanms** [comment]
The PR looks fine to me. You will need Jon's signoff here. Also curious, what regression testing process in this space looks like.

**Comment by danmoseley** [comment]
Which Jon? @jonsequitur  ?

**Comment by danmoseley** [comment]
Oh, @jmarolf 

(We're all interested in this PR because SDK codeflow is jammed and that's a bad thing)

**Review by jmarolf — APPROVED** [review]

**Pull request merged**
